title: AI-gegenereerde afbeeldingen
hero_image: images/banner.png
description: Creëer afbeeldingen met generatieve AI met behulp van Adobe Firefly
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Schrijf een prompt
    completion:
      - engaged
  - 
    title: Stijlen en effecten
    completion:
      - internal
  - 
    title: Wat kun je nu doen?
    completion:
      - external
