title: AI generated images
hero_image: images/banner.png
description: Create images with generative AI using Adobe Firefly
version: 1
listed: false
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
