---
title: Imagens geradas com a IA
hero_image: images/banner.png
description: Cria imagens com IA generativa usando Adobe Firefly
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: O que vais fazer
  - title: Escreve um prompt
    completion:
      - engaged
  - title: Estilos e efeitos
    completion:
      - internal
    completion:
      - external
