---
title: Im치genes generadas por IA
hero_image: images/banner.png
description: Crea im치genes con IA generativa usando Adobe Firefly
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Lo que har치s
  - title: Escribe una instrucci칩n
    completion:
      - engaged
  - title: Estilos y efectos
    completion:
      - internal
    completion:
      - external
