title: Images générées par l'IA
hero_image: images/banner.png
description: Crée des images avec l'IA générative en utilisant Adobe Firefly
version: 1
listed: false
copyedit: false
last_tested: "2024-06-27"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Écrire un prompt
    completion:
      - engaged
  - 
    title: Styles et effets
    completion:
      - internal
  - 
    title: Que peux-tu faire maintenant ?
    completion:
      - external
