---
title: Immagini generate dall'intelligenza artificiale
hero_image: images/banner.png
description: Crea immagini con l'intelligenza artificiale generativa utilizzando Adobe Firefly
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Cosa creerai
  - title: Scrivi un prompt
    completion:
      - engaged
  - title: Stili ed effetti
    completion:
      - internal
    completion:
      - external
